### ISSUE TITLE
Does not work with older IE browsers: Object doesn't support property or method '__defineGetter__'

### ISSUE THREAD

**Issue by juhamust** [LittleHelicase/frequencyjs#1]
Code uses `__defineGetter__` method, which is not supported by IE9 and IE10. 

According to this source (http://stackoverflow.com/a/6825247/454985), the usage of defineProperty is preferred.

Link to source: https://github.com/LittleHelicase/frequencyjs/search?utf8=%E2%9C%93&q=__defineGetter__

**Comment by LittleHelicase** [comment]
I removed all the `__defineGetter__` calls and used define Property. I have no IE and cannot test it. Could you try it?

**Comment by juhamust** [comment]
Thanks for the quick turnaround. Tested with IE9 and it seems to work :+1:
